### ISSUE TITLE
rDCM tutorial

### ISSUE THREAD

**Issue by Joyce-Z-J** [translationalneuromodeling/tapas#131]
![Screenshot 2021-03-22 at 16 01 46](https://user-images.githubusercontent.com/81119841/112010883-009a5880-8b28-11eb-81c8-f5354d1124d3.png)
Hi there,

First I would like to thank you for launching the rDCM toolbox and sharing the codes. 

So sorry to bother you with a very simple and stupid question: I ran rDCM in Matlab 2017a on macOS bigsur and when I coded "tapas rdcm tutorial()" to launch the tutorial, it said that "Xcode is installed, but its license has not been accepted. Run Xcode and accept its license agreement" (see screenshot).

Would you mind telling me why this happened and how to solve this problem?

Thank you so much for your time! Looking forward to your reply :)

All the best,
Joyce Jiang

**Comment by StefanFraessle** [comment]
Hi Joyce,

Thanks a lot for your interest in the rDCM toolbox - I hope it will be useful for you :)

rDCM uses mex files for some of the computationally expensive operations - this is code that is written outside of MATLAB (typically a language, like C, that is beneficial in terms of speed) but can be compiled in order to be use in MATLAB. This mex file needs to be compiled in order to run properly. The toolbox performs this compilation automatically when you first launch the script. On MacOS, compilation is done using Xcode - however on your system, this does not seem to have worked.

My initial guess is that your Xcode version does not match with the operating system and/or MATLAB version that you have. This is what you need to fix in order to get the toolbox running properly :)

I did a quick Google search and you should find information on which Xcode version matches with your Matlab version [here](https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/SystemRequirements-Release2017a_SupportedCompilers.pdf). Whether that also works on BigSur, I do not know.

Hope this helps.

All the best,
Stefan
