### ISSUE TITLE
Missing tics

### ISSUE THREAD

**Issue by nickmi12** [translationalneuromodeling/tapas#133]
Dear TAPAS-Team,

i have a problem with handling the PULS.log file created by our PPG, 3T SIEMENS MRI. Apparently, there are missing Tics and therefore data points (around 300) in our files. Does the Toolbox account for that by taking the time stamps from the info.log file anyways and thus just leaving these "spaces" in blank? I'm worried that the remaining points are just being put together which would create an unwanted time shift... In this case we probably would have to manually correct the .log file.

![image](https://user-images.githubusercontent.com/82827075/115262565-f4a8b300-a134-11eb-98f8-8c1dbef68211.png)

Also, we sometimes have uncompleted scans at the very end of a run: does the align-scan function include the last full scan or should we also correct this manually?

Thank you very much in advance for helping me out with these questions!
Nick

**Comment by mrikasper** [comment]
Dear Nick,

my apologies for the late reply. I presume physio should take care of the missed tics, because it assigns absolute times to the cardiac events, see `tapas_physio_read_physlogfiles_siemens_tics.m`, l.169ff:

```
cTics           = double(C{1});
[...]
 tCardiac        = cTics*dtCardiac  - log_files.relative_start_acquisition;
```

With respect to the uncompleted scans, I think the tics format again should be unproblematic, because the `info.log` has the same time scale (tics) as the pulse file.

So in short, I don't think you have to manually adjust your files. Have a try and compute the `multiple_regressors` and then look at the resulting F-contrasts via `tapas_physio_report_contrasts`. Especially for the cardiac data, the spatial noise patterns (e.g., [last figure in our paper](https://www.sciencedirect.com/science/article/pii/S016502701630259X#fig0045)) are very reproducible over subjects (basilar artery, circle of Willis, aquaeduct, ACC, insula, ventricles).

All the best,
Lars
