### ISSUE TITLE
rDCM set options

### ISSUE THREAD

**Issue by Joyce-Z-J** [translationalneuromodeling/tapas#137]
Dear Stephan,

Sorry to bother you but would you mind me asking a question regarding the function 'tapas_rdcm_set_options'?

When I was running the code, an error message showed up: unrecognized function or variable 'input_options' (see attached screenshot). Could you please tell me what kind of data or information do I need to provide for 'input_options' to address this problem?

Thank you so much for your time and help! :)

All the best,
Joyce

![Screenshot 2021-05-31 at 20 13 04](https://user-images.githubusercontent.com/81119841/120229097-b8e12d00-c24c-11eb-94d5-ef7b6840e9ae.png)

**Comment by StefanFraessle** [comment]
Hi Joyce,

Thank you very much for your interest in the rDCM toolbox - I hope it proves valuable for you.

In principle, `tapas_rdcm_set_options.m` specifies a whole set of options and settings that are necessary in order to run rDCM. The function sets all of these fields to default values, so that you don't have to set anything yourself if you don't want to deviate from the default settings. However, sometimes, it might make sense to change some of the default settings (e.g., the filter strength, or the p0 values). This is where `input_options` comes into play. This structure allows you to provide your own values for these options and/or settings and the rDCM code will then automatically overwrite the default settings with what you have provided. If you define input_options as an empty array, rDCM will (as already highlighted above) stick with the default settings. 

The way you set that correctly is when calling the main rDCM routine `tapas_rdcm_estimate.m`. Here is the general form of the function call:

`[output, options] = tapas_rdcm_estimate(DCM, type, options, methods)`

Hence, if you don't provide an options structure by writting

`[output, options] = tapas_rdcm_estimate(DCM, type, [], methods)`

you will run rDCM model inversion with the default settings (which I presume is what you want to do?).

Hope this helps.

With very best wishes,
Stefan
