### ISSUE TITLE
PhysIO: when respiratory file is empty?

### ISSUE THREAD

**Issue by jamyandy** [translationalneuromodeling/tapas#151]
Hi.. I was wondering if some of you had to deal with some empty files (empty resp. e.g. if the resp. belt was not properly fixed). Should we then not run PhysIO at all, or add empty resp. regressors?
Any input on this will be greatly appreciated,
Thanks and Best,
<img width="762" alt="emptyResp" src="https://user-images.githubusercontent.com/83708634/126600846-08a57ecf-d991-4c4e-bc7d-a89efb8956e1.png">

J.A

**Comment by mrikasper** [comment]
Dear @jamyandy,

I think you should just use the cardiac models in this case and leave the respiratory file empty in the `log_files` struct, so that these parts are ignored. 

Having all-zero columns in your design matrix makes those betas undefined and cannot explain any variance. I am sure SPM and other major analysis packages deal with that just fine, but it it not meaningful and does not help the physiological noise correction.

I hope that helps!

All the best,
Lars
