### ISSUE TITLE
A question about reward magnitude in HGF

### ISSUE THREAD

**Issue by XyZhouPsy** [translationalneuromodeling/tapas#175]
Hi guys,

I am trying to use HGF in my experiment. But I got a question of usage of HGF regarding my experiment design.

In my experiment, I used reversal learning task. And I got two conditions, namely reward-seeking and punishment-avoiding. In reward-seeking, the two options may have two outcomes (i.e., 1 as reward, 0 as neutral). Then in punishment-avoiding, the two options may have another outcomes (i.e., -1 as punishment, 0 as neutral).

I read the comments in _tapas_softmax_binary_config_. It said "This observation model expects the first column of the input matrix to contain the outcomes: 1 or 0 for each trial. The SECOND COLUMN of the input matrix is expected to contain the rewards for OPTION 0 and the THIRD COLUMN the rewards for OPTION 1. If the input matrix contains only one column, the rewards are all assumed to be equal to 1." 
Should I have the last two columns of input matrix contain all ONES elements in reward-seeking while the last two columns contain all NEGATIVE ONES elements in punishment-avoiding.
Or just fit the data with the same model, since the magnitudes between two outcomes in both conditions are one. (But in RW model, we shouldn't do this, should we? After all, the expectation and outcomes in both conditions are different).
Otherwise is there some other ways to be used with my design. 

Thank you,
Best wishes,

Xy

**Comment by chmathys** [comment]
Dear Xy,

It's hard for me to give advice on setting this up because I don't know what exactly your hypothesis is.

How you proceed would also have to depend on whether the two conditions are related. Are outcomes in one condition predictive of future outcomes in the other condition? etc.

The coding of inputs you describe would work if you had two (categories of) inputs, each associated with a probability of winning (summing to 1), but with reward (conditional on winning) varying from trial to trial.

Best wishes,
Christoph
