### ISSUE TITLE
PhysIO crashes with `Out of memory` on R2017b

### ISSUE THREAD

**Issue by nbeliy** [translationalneuromodeling/tapas#180]
Hi,

trying to run example from `tapas/examples/5.1.2/PhysIO/Siemens_VD/PPU3T`,
the ` tapas_physio_main_create_regressors` crashes:

```matlab
>> siemens_vd_ppu3t_matlab_script()
Defaults settings have been modified by file(s):
  /home/beliy/Documents/MATLAB/spm_my_defaults.m
Modified fields: mat 
Warning: Ignoring given sampling intervals, using dt = 2.5 ms (tics) instead 
Warning: Invalid trend type '3'.. assuming 'linear'. 
Out of memory. Type HELP MEMORY for your options.

Error in tapas_physio_filter_respiratory (line 133)
rpulset_padded(1:n_pad) = padding_window(1:n_pad) .* rpulset_padded(1:n_pad);

Error in tapas_physio_main_create_regressors (line 218)
                [ons_secs.fr, verbose] = tapas_physio_filter_respiratory( ...

Error in siemens_vd_ppu3t_matlab_script (line 66)
physio = tapas_physio_main_create_regressors(physio);
```

After investigation, in file `tapas_physio_filter_respiratory`,
the windows `padding_window` (line 131) and `rpulset_padded` (line 132)
are created as column and vector respectively:
```
133 rpulset_padded(1:n_pad) = padding_window(1:n_pad) .* rpulset_padded(1:n_pad);
K>> size(padding_window)
ans =
           1      160003
K>> size(rpulset_padded)
ans =
      169391           1
K>> 
```

which in turn, during the execution of:
```matlab
rpulset_padded(1:n_pad) = padding_window(1:n_pad) .* rpulset_padded(1:n_pad);
```
creates a huge matrix.

A fix, that worked for me is just to force both window into column vectors.

It is probably related to the matalb version (mine is 2017b). 

If needed, I can create a pull request (fix is stupid).

**Comment by mrikasper** [comment]
Dear Nikita,

Thank you for using PhysIO and reporting this error. Unfortunately, this is a known compatibility issue with SPM discussed in [this issue](https://github.com/translationalneuromodeling/tapas/issues/166) as well.

It relates to the fact that a subfolder of SPM (`external/fieldtrip/external`) contains functions from different SPM toolboxes that shadow inbuilt functions from Matlab toolboxes. This has been fixed in the latest SPM/Fieldtrip [development branches](https://github.com/spm/spm), but I am not sure it's already in an official release.

If you cannot upgrade SPM, there is an easy fix: Just remove the subfolders of SPM from your path, i.e., use `addpath('path/to/spm12')` instead of `addpath(genpath('path/to/spm12'))`. Maybe run `rmpath(genpath('path/to/spm12'))` before the `addpath`, just to be sure it has not been added already. If you run `tapas_physio_init`, it will also issue a warning (though no error), if the subfolders of SPM are in the path.

Let me know what you think and how we can better document this behavior, e.g., having an error instead of a warning in the init function, or providing an entry in our [FAQ](https://gitlab.ethz.ch/physio/physio-doc/-/wikis/FAQ) to mention this issue. In general, it's a good idea to search this issue forum for keywords to your error, especially in the closed issues that are hidden in the default view.

All the best,
Lars
