### ISSUE TITLE
PhysIO toolbox heartbeat modeling

### ISSUE THREAD

**Issue by s-kline** [translationalneuromodeling/tapas#2]
The warning 'there seem to be skipped heartbeats in the sequence of pulses' occurs for some subjects only if the last scan is used as a reference for time matching. This bug (?) occurs for 4 out of 36 subjects.
Siemens Scanner and ECG cardiac files were used.

![first_scan_asref](https://user-images.githubusercontent.com/31928139/30970098-959a74e6-a464-11e7-849a-a08e2fe218aa.jpg)
![last_sca_asref](https://user-images.githubusercontent.com/31928139/30970099-95e20ae0-a464-11e7-9919-d0c63307da3a.jpg)

**Comment by kasperla** [comment]
Thank you for using the toolbox and your feedback!
That's very interesting! 

- As you can see in the screenshots, the choice of a different time stamp (first vs last) selects a shifted portion of the time series (by about 20 seconds, it seems)
- My guess would be that therefore the start of the time series (that is used to generate the template for matching the cardiac peaks) is different (noisier?) and therefore the template itself is more imprecise and misses heartbeats. 
- It is puzzling though that this is systematic for the last vs first scan time stamp. And if so, I would expect it the other way around, since people calm down in the scanner and the template should be more reliable when excluding the start of the run.
- For an in-depth analysis: Could you please send me such a logfile together with the two different PhysIO batch files you used to create the plots?
- Alternatively, `.fig`-files would be helpful for both screenshots, so that one can zoom a bit and see the actual time series.

Thank you and all the best,
Lars
