### ISSUE TITLE
adapting for multiband?

### ISSUE THREAD

**Issue by mayhewsd** [translationalneuromodeling/tapas#29]
Hi, firstly wanted to say great job on the toolbox, really great, very useful piece of software youve put together.
secondly, i have a question id appreciate some advice on please?
From looking through the code it doesnt seem to explicitly deal with multiband slice excitation, so ive been trying to figure out how to adapt it.
But, as the code downsamples the slice aligned retroicor regressors (e.g. c_phase) to volume timing (e.g. c_sample_phase) which are used to form the final matrix R, it doesnt seem like i need to do anything? As the regression isnt being done on a slice by slice basis in the GLM?
Presumably as long as I have enough slice excitations in a TR to be able to reasonably estimate the card/resp phase per slice, then downsampling to volume temporal resolution will work ok?
thanks
Steve

**Comment by mrikasper** [comment]
Dear Steve,

thank you for your interest in the toolbox. I am glad you find it useful.

You are right, at the moment there is no specific handling of multiband data in the PhysIO code, but there certainly will be in the not-to-distant future, since it seems to be a very frequent user request :-)

In the meantime, have a look at [this thread](https://github.com/translationalneuromodeling/tapas/issues/17#issuecomment-412063737) (and the one linked in there) on how to conceptualize multiband in the PhysIO context and use a workaround.

With respect to your specific question, I would also say that modeling per volume is OK as long as the heart rate does not change dramatically within TR. Alternatively, if you put a vector for the `onset_slice` parameter, one design matrix is output aligned to each specified slice, so you can compare their performance.

In general, choose a slice that you are most interested in as your `onset_slice` and be aware that the counting index is about temporal order and not about spatial location. More details in above thread.

All the best,
Lars
