### ISSUE TITLE
Precision-weighting of prediction errors

### ISSUE THREAD

**Issue by Leone-G** [translationalneuromodeling/tapas#41]
Dear Dr Mathys and HGF experts,

I am running a 2-levels HGF model using the hgf_binary.m function to explore internal beliefs about the response to the upcoming trial given the previous trial history, and related prediction errors (PE). I would kindly ask to you some elucidtions about how the precision weighting (psi) on PE is computed.

According to Equation 6 in Iglesias et al. (2013) and Equation 4 in Paliwal et al. (2014), psi is the ratio between pihat at the level below (representing the precision of the prediction about input from the level below) and pi at the current level (representing the precision of the beliefs at the current level):
```
psi = pihat(l-1)/pi(l). 
```
In the hgf_binary.m code (line 253-255) this is true for the third level but not for the second level:
```
psi        = NaN(n-1,l);
psi(:,2)   = 1./pi(:,2);
psi(:,3:l) = pihat(:,2:l-1)./pi(:,3:l);
```
Does the second level represent an exception to Iglesias et al. equation?
According to Equation 41 in Mathys et al. (2011), the precision of the prediction at the current level: 
```
pi2 = pihat2 + 1/pihat1,
```
resulting as the inverse of uncertainty sa2. Therefore, if psi2 = 1/pi2 and sa2 = 1/pi2, then psi2=sa2. 
I am wondering if, by doing so, when I compute precision-weighted PE (epsi2) I am weighting PE for the precision or for the uncertainty. As, on average, in my results uncertainty is relatively low (with consequent high precision pi), I obtained very low values for epsi2. Should I use: psi(:,2)=pihat(:,1)/pi(:,2)? 

I have a question I'd like to ask you: would it be correct to use raw PE in an fMRI study, if I don't want to make any inference about uncertainty and precision of the prediction, but to focus only on how discrepancies between internal beliefs and real outcomes are processed?

Thank you very much for your attention.
Best wishes,

Giovanni

Ref.
Iglesias et al. (2013): https://doi.org/10.1016/j.neuron.2013.09.009
Paliwal et al. (2014):  https://doi.org/10.3389/fnhum.2014.00428
Mathys et al. (2011): https://doi.org/10.3389/fnhum.2011.00039

**Comment by chmathys** [comment]
Dear Giovanni,

Please see my explanations below.

On 21 December 2018 at 2:29:33 pm, Leone-G (notifications@github.com) wrote:

Dear Dr Mathys and HGF experts,

I am running a 2-levels HGF model using the hgf_binary.m function to
explore internal beliefs about the response to the upcoming trial given the
previous trial history, and related prediction errors (PE). I would kindly
ask to you some elucidtions about how the precision weighting (psi) on PE
is computed.

According to Equation 6 in Iglesias et al. (2013) and Equation 4 in Paliwal
et al. (2014), psi is the ratio between pihat at the level below
(representing the precision of the prediction about input from the level
below) and pi at the current level (representing the precision of the
beliefs at the current level):

psi = pihat(l-1)/pi(l).

In the hgf_binary.m code (line 253-255) this is true for the third level
but not for the second level:

psi        = NaN(n-1,l);
psi(:,2)   = 1./pi(:,2);
psi(:,3:l) = pihat(:,2:l-1)./pi(:,3:l);

Does the second level represent an exception to Iglesias et al. equation?

Yes. This is mentioned on page 8 of the supplementary material of Iglesias
et al.


According to Equation 41 in Mathys et al. (2011), the precision of the
prediction at the current level:

pi2 = pihat2 + 1/pihat1,

resulting as the inverse of uncertainty sa2. Therefore, if psi2 = 1/pi2 and
sa2 = 1/pi2, then psi2=sa2.
I am wondering if, by doing so, when I compute precision-weighted PE
(epsi2) I am weighting PE for the precision or for the uncertainty. As, on
average, in my results uncertainty is relatively low (with consequent high
precision pi), I obtained very low values for epsi2. Should I use:
psi(:,2)=pihat(:,1)/pi(:,2)?

Your options are explained in detail on pages 7-10 and 15-16 of the
supplementary material of Iglesias et al. In order to get uncertainty and
precision of the prediction at the first level, you should use equation D.1
on page 16.


I have a question I'd like to ask you: would it be correct to use raw PE in
an fMRI study, if I don't want to make any inference about uncertainty and
precision of the prediction, but to focus only on how discrepancies between
internal beliefs and real outcomes are processed?

This makes sense to me.

Best wishes,

Christoph


Thank you very much for your attention.
Best wishes,

Giovanni

Ref.
Iglesias et al. (2013): https://doi.org/10.1016/j.neuron.2013.09.009
Paliwal et al. (2014): https://doi.org/10.3389/fnhum.2014.00428
Mathys et al. (2011): https://doi.org/10.3389/fnhum.2011.00039

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/translationalneuromodeling/tapas/issues/41>, or mute
the thread

**Comment by Leone-G** [comment]
Dear Dr Mathys,

Thank you very much for your explanations and for your time. Everything is much clearer to me now.

Best wishes,

Giovanni
