### ISSUE TITLE
HGF: Gaussian noise on responses on a continuous scale

### ISSUE THREAD

**Issue by ianthe00** [translationalneuromodeling/tapas#49]
Dear Dr Mathys,

I wonder whether you know of any paper that has used "gaussian_obs" as response model for empirically observed responses on a continuous scale (as opposed to the "simulated" responses that you used as example in your documentation). 

Thanks in advance

Best,
ianthe

**Comment by chmathys** [comment]
Dear ianthe,

No, I’m not aware of such a paper, but there may be ones that I’m not aware
of. This reflects the prevalence of paradigms with binary or categorical
choices. In general, there is much to be said in favour of paradigms with
choices on a continuous scale because such observations contain more
information than categorical choices.

Best wishes,
Christoph

On 3 March 2019 at 8:26:50 pm, ianthe00 (notifications@github.com) wrote:

Dear Dr Mathys,

I wonder whether you know of any paper that has used "gaussian_obs" as
response model for empirically observed responses on a continuous scale (as
opposed to the "simulated" responses that you used as example in your
documentation).

Thanks in advance

Best,
ianthe

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/translationalneuromodeling/tapas/issues/49>, or mute
the thread
