### ISSUE TITLE
HGF: Multiple cues -> binary outcomes

### ISSUE THREAD

**Issue by mpcoll** [translationalneuromodeling/tapas#60]
Dear Dr Mathys and HGF users,

I used the HGF successfully in the past to successfully model learning in simple designs but now I am tackling a more complex design and I was wondering if you had any advice. 

In brief, at each trial, the agent sees one of 14 cues which is probabilistically associated with a binary outcome (rewarded or not). I am trying to track the agent’s learning of the cue-> reward association. My issue here is that with this number of cues I can’t figure out how to code the inputs in contingency space as I would do in a design with 2 cues. I tried treating the problem as a multi-arm bandit situation with 14 arms but this does not seem optimal and leads to poor fits compared to simple RW models.

I was therefore wondering if by any chance you had any suggestion on how to tackle this design with the HGF or would know about any papers doing something similar?

Thank you for your help and best wishes,

MP

**Comment by chmathys** [comment]
Dear MP,

You don’t need to code in contingency space in your case. This is a device
you can use when you’re learning two mirrored associations at once. You
seem to have 14 independent associations which need to be learned
independently.

You also don’t seem to have a multi-armed bandit paradigm since agents
don’t get a choice to play or not play an option. The most straightforward
thing to do here seems to use 14 independent binary HGFs, one for each cue.
Depending on the number of trials for each cue and the volatility
structure, it may well be the case that RW outperforms the HGF here. The
fewer trials and the simpler the volatility structure, the greater the
advantage for the simpler model.

Best wishes,
Christoph

On 7 June 2019 at 5:49:21 pm, mpcoll (notifications@github.com) wrote:

Dear Dr Mathys and HGF users,

I used the HGF successfully in the past to successfully model learning in
simple designs but now I am tackling a more complex design and I was
wondering if you had any advice.

In brief, at each trial, the agent sees one of 14 cues which is
probabilistically associated with a binary outcome (rewarded or not). I am
trying to track the agent’s learning of the cue-> reward association. My
issue here is that with this number of cues I can’t figure out how to code
the inputs in contingency space as I would do in a design with 2 cues. I
tried treating the problem as a multi-arm bandit situation with 14 arms but
this does not seem optimal and leads to poor fits compared to simple RW
models.

I was therefore wondering if by any chance you had any suggestion on how to
tackle this design with the HGF or would know about any papers doing
something similar?

Thank you for your help and best wishes,

MP

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/translationalneuromodeling/tapas/issues/60?email_source=notifications&email_token=AEXIN7OZZX56ZM3LT2XUEELPZJ7QDA5CNFSM4HVYIZWKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYJDDJA>,
or mute the thread
