### ISSUE TITLE
PhysiO : before or after normalization

### ISSUE THREAD

**Issue by CarolineLndl** [translationalneuromodeling/tapas#70]
Hello,
I am currently analysing task-related fMRI data. At the second level I used univariate and multivariate analyses (MVPA)
However, I would like to know what is best: running the pipeline for Noise ROI extraction on functionnal image before normalization or after normalization. I try both u-images (realigned) and swu-images (realigned, normalized and smoothed images). At the second level (univariate analyse) I get much broader activations in the second case and the result does not seem very "clean" to me.

Thanks in advance for your advices

Caroline

**Comment by mrikasper** [comment]
Dear Caroline,

your question is related to another [recent issue](https://github.com/translationalneuromodeling/tapas/issues/66). Please have a look at the answers posted there as well.

In brief, I think using unsmoothed images should be more conservative, i.e., only removing physiological noise, not activation from adjacent gray matter. However, due to the lower SNR, your sensitivity characterizing the physiological noise might be reduced before smoothing. Normalization shouldn't make a difference, but the masks (or tissue probability maps) for the extraction and the functional data should be in the same space, i.e., either both normalized or un-normalized.

In terms of "broader activation", do you mean for your task or for the physiological noise F-contrasts? And in what way are the results not very clean.

There are a lot of considerations when specifying the noise ROIs, e.g., thresholding of the tissue probability maps and erosion/cropping of boundary voxels. Please look at the aforementioned issue for a full discussion.
