### ISSUE TITLE
HGF_jget model fitting queries

### ISSUE THREAD

**Issue by cmill22** [translationalneuromodeling/tapas#74]
Dear Dr Mathys,

I am currently trying to fit a 2-level HGF_jget model to continuous data and have a couple of queries regarding this:

1. Confusion about logzemu: my understanding of logzemu is that it is the decision noise parameter, thus I thought fixing this to 0 would result in an HGF perfectly fitted to participant responses (in other words, participants produce responses exactly according to their beliefs, reflected in the HGF). However when I tested this out it seems the model does not get fitted exactly to participant responses. In addition, I have noticed fixing logzemu to 0 fixes all other parameters in the model (even those that are not fixed). Would you be able to clarify the reason for these observations?

2. General question about model fitting: My dataset consists of 74 participants with each of the 6 task conditions fitted separately. This means the output from the HGF is 444 graphs/LME values. I am unsure of the best way to measure when I have found the optimal fit (and avoid overfitting) across so many participants, particularly when there often seem to be some participants that fit a model much better than others.

4. During model fitting I keep encountering the error message: "Negative posterior precision. Parameters are in a region where model assumptions are violated." I noticed in the scripts it suggests lowering the omega values but I seem to still get this error- would you be able to explain what this error means and why changing the omegas should counteract it?

Apologies for the very basic questions but thank you so much for your kind help with this.
Very best wishes,
Chantal

**Comment by chmathys** [comment]
Dear Chantal - please see my answers below.

Best wishes,
Christoph

On 28 October 2019 at 2:39:15 pm, cmill22 (notifications@github.com) wrote:

Dear Dr Mathys,

I am currently trying to fit a 2-level HGF_jget model to continuous data
and have a couple of queries regarding this:

   1.

   Confusion about logzemu: my understanding of logzemu is that it is the
   decision noise parameter, thus I thought fixing this to 0 would result in
   an HGF perfectly fitted to participant responses (in other words,
   participants produce responses exactly according to their beliefs,
   reflected in the HGF). However when I tested this out it seems the model
   does not get fitted exactly to participant responses. In addition, I have
   noticed fixing logzemu to 0 fixes all other parameters in the model (even
   those that are not fixed). Would you be able to clarify the reason for
   these observations?

All model fitting requires a noise parameter as a kind of safety valve.
Since a parameter setting that produces the exact sequence of observations
may not exist (and normally doesn’t exist, for any model, even a simple
linear regression - as they say: all models are wrong, but some are
useful), you always need to allow for a difference between the actual and
the predicted observation. So you should never fix decision noise to 0.
Furthermore, when the optimization algorithm has trouble fitting the model,
it often helps to increase the prior variance of the decision noise.


   1.


   Log model evidence: I have noticed on some occasions running the same
   model twice (or running different models that give the same output
   parameter values) with the same participants (so same task inputs and
   participant responses) produces different (sometimes vastly different) log
   model evidence values when these should surely be stable?

You are right: since the current optimization algorithm is deterministic,
running it twice should produce the exact same results both for parameter
estimates and model evidence. Perhaps what you describe happens because
you’ve fixed decision noise to 0. If fixing that doesn’t resolve this,
please post a reproducible example of this behaviour.


   1.


   General question about model fitting: My dataset consists of 74
   participants with each of the 6 task conditions fitted separately. This
   means the output from the HGF is 444 graphs/LME values. I am unsure of the
   best way to measure when I have found the optimal fit (and avoid
   overfitting) across so many participants, particularly when there often
   seem to be some participants that fit a model much better than others.

You should download SPM (
https://www.fil.ion.ucl.ac.uk/spm/software/download/) and use the function
spm_BMS(). See the documentation of that function and the following papers:

Stephan, K. E., Penny, W. D., Daunizeau, J., Moran, R. J., & Friston, K. J.
(2009). Bayesian model selection for group studies. NeuroImage, 46(4),
1004–1017. https://doi.org/10.1016/j.neuroimage.2009.03.025

Rigoux, L., Stephan, K. E., Friston, K. J., & Daunizeau, J. (2014).
Bayesian model selection for group studies—Revisited. NeuroImage, 84,
971–985. https://doi.org/10.1016/j.neuroimage.2013.08.065
The function spm_BMS() will do a formal model comparison for you. However,
it is important to remember that any results of formal comparisons are
subordinate to the following three criteria:

1. The model should be able to address your question of interest

2. Your prior predictive distribution should be plausible

3. Your posterior predictive distribution should reproduce the patterns
observed in the data

Apologies for the very basic questions but thank you so much for your kind
help with this.
Very best wishes,
Chantal

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/translationalneuromodeling/tapas/issues/74?email_source=notifications&email_token=AEXIN7LEZ6Z52376OGIJ66DQQ3TQHA5CNFSM4JF2JAM2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HUYPPWQ>,
or unsubscribe
