### ISSUE TITLE
HGF: Gamma/Beta distributions

### ISSUE THREAD

**Issue by HuSuyi** [translationalneuromodeling/tapas#77]
Dear Dr. Mathys

First of all, I would like to thank you for your feedback on my last question. It helped us a lot to develop an HGF-based model to simulate tinnitus perception with the TAPAS toolbox. However, I still have an open question that I would like to ask you:

We want to use a gamma (or beta) distribution instead of a Gaussian to add some constraints to the last layer (other layers remain Gaussian). My question is whether this is possible because they come from exponential families and whether there are any similar implementations in the tapas toolbox. I would be very grateful if you could give us some hints on how to derive Variational Energy and update equations using non-gaussian distribution in the last layer. 

Thank you for your time. 

Best Regards
Suyi Hu

**Comment by chmathys** [comment]
Dear Suyi,

I’ve thought about your suggestion. It's interesting, and I see at least
two ways to do this. However, this would require a little work - on the
scale of a small research project (e.g., a Masters project). If you’d like
to proceed with this, I suggest you write me directly because this is
beyond the scope of this forum.

Best wishes,
Christoph

On 11 November 2019 at 12:23:09 pm, suyihu (notifications@github.com) wrote:

Dear Dr. Mathys

First of all, I would like to thank you for your feedback on my last
question. It helped us a lot to develop an HGF-based model to simulate
tinnitus perception with the TAPAS toolbox. However, I still have an open
question that I would like to ask you:

We want to use a gamma (or beta) distribution instead of a Gaussian to add
some constraints to the last layer (other layers remain Gaussian). My
question is whether this is possible because they come from exponential
families and whether there are any similar implementations in the tapas
toolbox. I would be very grateful if you could give us some hints on how to
derive Variational Energy and update equations using non-gaussian
distribution in the last layer.

Thank you for your time.

Best Regards
Suyi Hu

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/translationalneuromodeling/tapas/issues/77?email_source=notifications&email_token=AEXIN7OM2SOQHNDJWZ3UMELQTE6BZA5CNFSM4JLUEVDKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HYMJAUA>,
or unsubscribe
