### ISSUE TITLE
rDCM: how can I apply the sparsity constraints?

### ISSUE THREAD

**Issue by davidevaleriani** [translationalneuromodeling/tapas#82]
Hi!
Thank you so much for developing and sharing the toolbox.

I am using your sparse rDCM on 3T fMRI data during task production. From your paper (Frässle et al. 2018), I was expecting the model to already automatically reduce the density of the connectivity matrix (`Ep.A`). However, I get a density of over 98% for most of the subjects. Do you have any idea why is that?

I use `tapas_rdcm_estimate(DCM, 'r', options, 2)`, with the default p0_all (range 0.05;0.05;0.95).

Thanks,
Davide

**Comment by StefanFraessle** [comment]
Hi Davide,

Thank you for the kind words - it's great that you are giving the toolbox a try :)

The generative model of rDCM is designed in a way that sparsity is induced by binary indicator variables that are multiplied with the posterior parameter estimates. This means that the Ep.A matrix still contains all the posterior parameter estimates – the fact that you see some 0s is probably because those values were very close to zero and were thus just set to zero for numerical reasons. The sparsity structure itself is encoded in the Ip.A field, which contains the posterior probabilities of the binary indicator variables.
 
Note that you still need to choose a threshold for defining whether a connection is present or not based on these posterior probabilities. We have eluded to this point in our rDCM paper (Frässle et al., 2018) and suggested the posterior odds ratio as a principled way of doing this. A (sensitive) threshold that we typically use is log(1/10), which means that there is not enough evidence for the absence of a connection, and hence the connection is not pruned. You can implement this by computing
 
lb = log(1/10);
Ip_final = log(Ip.A ./ (1-Ip.A)) > lb;
 
The final sparse posterior parameter matrix is then computed using
 
Ep.A .* Ip_final
 
As a final note: We have shown that for low SNR and/or slow TR data (which is likely to be the case for your 3T dataset), rDCM is overly conservative – meaning that for small p0 values (e.g., 0.05 etc), you might end up with a completely sparse matrix. If this is the case, you might want to adapt the range of p0 values that you test to render the model less conservative. Of course, you should be aware of this change and critically evaluate whether it is justified in your situation.

I hope this is helpful. Let me know if you have further questions.
 
With very best wishes,
Stefan
